import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const PAGE_COUNT = 100;

function buildPageHtml(mode: 'external' | 'inline'): string {
  const iconMarkup =
    mode === 'external'
      ? Array.from(
          { length: 10 },
          () =>
            '<svg viewBox="0 0 24 24" class="size-5" aria-hidden="true"><use href="/design-assets/icons/square.svg?v=0.1.0#asset"></use></svg>',
        ).join('')
      : Array.from(
          { length: 10 },
          () =>
            '<svg viewBox="0 0 24 24" class="size-5" aria-hidden="true"><rect x="5" y="5" width="14" height="14" rx="2" fill="none" stroke="currentColor" stroke-width="1.75"/></svg>',
        ).join('');

  return `<!doctype html><html><body>${iconMarkup}</body></html>`;
}

async function sumFileSizes(dir: string, prefix: string): Promise<number> {
  let total = 0;
  const files = await readdir(dir);
  for (const file of files) {
    if (!file.startsWith(prefix)) continue;
    const info = await stat(join(dir, file));
    total += info.size;
  }
  return total;
}

async function main(): Promise<void> {
  const outDir = join(ROOT, 'dist-prerender-measure');
  await mkdir(outDir, { recursive: true });

  for (let i = 0; i < PAGE_COUNT; i += 1) {
    await writeFile(
      join(outDir, `external-${i}.html`),
      buildPageHtml('external'),
    );
    await writeFile(join(outDir, `inline-${i}.html`), buildPageHtml('inline'));
  }

  const externalSum = await sumFileSizes(outDir, 'external-');
  const inlineSum = await sumFileSizes(outDir, 'inline-');

  const table = `# Storage at scale (100 prerendered pages, 10 icons each)

| Strategy | Total HTML (bytes) | Avg per page |
|---|---|---|
| External-file \`<use href>\` | ${externalSum} | ${Math.round(externalSum / PAGE_COUNT)} |
| Inline SVG markup | ${inlineSum} | ${Math.round(inlineSum / PAGE_COUNT)} |

Generated by \`apps/demo-react/scripts/measure-prerender.ts\`.
`;

  await writeFile(join(ROOT, 'STORAGE_AT_SCALE.md'), table);
  console.log(table);
}

main().catch(console.error);
